import argparse
from openai import OpenAI
import pandas as pd
import os

def main():
    parser = argparse.ArgumentParser(description="CodeCraft-CLI is a \
                                 command-line tool designed to modify CSV files using OpenAI's \
                                 GPT model. The tool generates Python code based on your input, executes the \
                                 code to process the CSV file, and saves the updated CSV file. It allows users \
                                 to leverage the power of GPT to automate and streamline CSV file manipulation tasks")

    parser.add_argument("input_file", type=str, help="Csv file to be processed")
    parser.add_argument("output_file", type=str, help="Output file to be created")
    parser.add_argument("prompt", type=str, help="Prompt for function/code to be generated by GPT and executed on the csv file")
    parser.add_argument("-v", "--verbose", help="Increase output verbosity", action="store_true")

    args = parser.parse_args()

    csv_text = get_csv_text(args.file)
    
    client = OpenAI()

    client.api_key = os.environ.get("OPENAI_API_KEY")

def generate_python_code():
    pass

def execute_python_code():
    pass

def get_csv_text(filename):
    df = pd.read_csv(filename)
    return df.to_string()

if __name__ == "__main__":
    main()